### ISSUE TITLE
Uses cl-muth:make-atomic-counter which doesn't exist

### ISSUE THREAD

**Issue by xach** [borodust/cl-flow#10]
cl-muth does not seem to have make-atomic-counter.

**Comment by borodust** [comment]
I saw it failing around 06/25. Should be already fixed. Does it fail still?

**Comment by borodust** [comment]
Oh, i see the report. Weird. I look into that.

**Comment by borodust** [comment]
[Looks like](http://report.quicklisp.org/2018-07-10/failure-report.html) it doesn't fail anymore. Thanks for the report!
