### ISSUE TITLE
Nickname clash with http://quickdocs.org/flow/

### ISSUE THREAD

**Issue by larsen** [borodust/cl-flow#8]
`cl-flow`'s nickname `flow` clashes with [flow](http://quickdocs.org/flow/)'s package name.

**Comment by borodust** [comment]
Thank you for the PR, but, unfortunately, those two systems (this and Shinmera's `flow`) would never be able to coexist. `:flow` nickname was chosen to have a sound symbol names for users who prefer to write fully qualified names, like `flow:atomically`, `flow:serially`, etc (more in this [guide](https://borodust.org/projects/cl-flow/getting-started/)). At the moment of lib creation, there was no such package clash, and the whole API was designed around that naming.

Same goes for `trivial-gamekit`and other projects in [bodge-projects](https://github.com/borodust/bodge-projects). Those will probably never find their way into  main quicklisp distribution, but I totally not going to change the names, If there would be a similar package clash.
